### ISSUE TITLE
will the build be updated to the latest stable mainstream release?

### ISSUE THREAD

**Issue by bitchecker** [nchevsky/systemrescue-zfs#9]
The latest stable release of systemrescue is 8.07 with a release date 2021-12-19.

Will this interesting project be updated?

**Comment by bitchecker** [comment]
UPDATE:
today they released the 9.00

**Comment by gvegidy** [comment]
Hi, I'm one of the developers of SystemRescue upstream.

We incorporated your serial console improvements and the reduced timeout in the bootloader until the system boots with default options into the just released SystemRescue 9.06.

Unfortunately we still won't risk distributing linked ZFS binaries due to the legal risks to the project.

But we recently included tooling like yay and the SystemRescue Modules (SRM) https://www.system-rescue.org/Modules/ that should make it much easier to add additional features to SystemRescue and distribute them. So should somebody be willing to regularly build and distribute SRM-files with ZFS or something similar, we are open for cooperation.

**Comment by nchevsky** [comment]
Thank you, @gvegidy! As time allows, I'll check out the upstream improvements and start preparing a new release.

**Comment by gvegidy** [comment]
Great! If you run into some issues or want to suggest some change to make your job easier, don't hesitate to open an issue in our bugtracker https://gitlab.com/systemrescue/systemrescue-sources/-/issues

**Comment by bill-mcgonigle** [comment]
Just wanted to leave a note saying it's great to see this discussion.

About CDDL: a few workarounds could be:

- shipping DKMS and having a r/w partition with overlayfs for the modules, so they would only need to be built once per version.  It would bloat the ISO by the size of build tools.  Something would need to understand if the boot media is USB or R/O optical.
- doing an Ubuntu remix with ZFS support already baked in - probably too much duplication work.
- eff it, not a real risk (IANAL)

Thanks for making the current ISO available - it's on my batbelt.
